(load "mk-vicare.scm")
(load "mk.scm")
(load "smt.scm")
(load "test-check.scm")

(load "../clpsmt-miniKanren/z3-driver.scm")
;;(load "../clpsmt-miniKanren/cvc4-driver.scm")
(load "../clpsmt-miniKanren/talk.scm")
(load "../clpsmt-miniKanren/radi-tests.scm")
(load "../clpsmt-miniKanren/radiw-concrete-tests.scm")
